// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJC9Jr90xSqXtLGFw5dERVWnDG_h408fM',
    appId: '1:800232142357:web:3ed802dba46ff40aa2801c',
    messagingSenderId: '800232142357',
    projectId: 'mahfooz-acocunts-app',
    authDomain: 'mahfooz-acocunts-app.firebaseapp.com',
    storageBucket: 'mahfooz-acocunts-app.firebasestorage.app',
    measurementId: 'G-7NDH9TQ532',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnh4xTm_UAcgY8QH2xH7HJw3lix0DU4PE',
    appId: '1:800232142357:android:ffd585f4e0453ef4a2801c',
    messagingSenderId: '800232142357',
    projectId: 'mahfooz-acocunts-app',
    storageBucket: 'mahfooz-acocunts-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDGGbEk6HHWMKeddAhhx3kRxssPBcT6g',
    appId: '1:800232142357:ios:7432591a9fbd1c01a2801c',
    messagingSenderId: '800232142357',
    projectId: 'mahfooz-acocunts-app',
    storageBucket: 'mahfooz-acocunts-app.firebasestorage.app',
    androidClientId: '800232142357-eqkpdtjbjr0018le7ctsgika5521faq5.apps.googleusercontent.com',
    iosClientId: '800232142357-2u8et6b02e4s4jkl6s9du6o4i0bpmtc9.apps.googleusercontent.com',
    iosBundleId: 'www.mahfooz.account.app.mehfoozAccountsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLDGGbEk6HHWMKeddAhhx3kRxssPBcT6g',
    appId: '1:800232142357:ios:7432591a9fbd1c01a2801c',
    messagingSenderId: '800232142357',
    projectId: 'mahfooz-acocunts-app',
    storageBucket: 'mahfooz-acocunts-app.firebasestorage.app',
    androidClientId: '800232142357-eqkpdtjbjr0018le7ctsgika5521faq5.apps.googleusercontent.com',
    iosClientId: '800232142357-2u8et6b02e4s4jkl6s9du6o4i0bpmtc9.apps.googleusercontent.com',
    iosBundleId: 'www.mahfooz.account.app.mehfoozAccountsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJC9Jr90xSqXtLGFw5dERVWnDG_h408fM',
    appId: '1:800232142357:web:f9b95d7ccbeab6afa2801c',
    messagingSenderId: '800232142357',
    projectId: 'mahfooz-acocunts-app',
    authDomain: 'mahfooz-acocunts-app.firebaseapp.com',
    storageBucket: 'mahfooz-acocunts-app.firebasestorage.app',
    measurementId: 'G-K837G3GJ8F',
  );
}
