import 'dart:io';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';

import '../../model/tx_item_ui.dart';
import '../../theme/app_colors.dart';

class TxDetailsPdfService {
  TxDetailsPdfService._private();
  static final TxDetailsPdfService instance = TxDetailsPdfService._private();

  final NumberFormat fmt = NumberFormat('#,##0.00');
  static pw.Font? _unicodeFont;

  Future<pw.Font> _font() async {
    _unicodeFont ??= pw.Font.ttf(
      (await rootBundle.load('assets/fonts/NotoSansArabic-Regular.ttf'))
          .buffer
          .asByteData(),
    );
    return _unicodeFont!;
  }

  bool _isRtl(String? s) {
    if (s == null || s.trim().isEmpty) return false;
    return RegExp(
      r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]',
    ).hasMatch(s);
  }

  pw.TextDirection _dir(String text) =>
      _isRtl(text) ? pw.TextDirection.rtl : pw.TextDirection.ltr;

  // -----------------------------------------------------------
  // PUBLIC FUNCTION
  // -----------------------------------------------------------
  Future<File> render(TxItemUi row) async {
    final pdf = pw.Document();
    final font = await _font();

    // ✅ REAL money logic
    final bool isCredit = row.cr > 0;
    final double rawAmount = row.amount;

    // 🔒 kill -0.00
    final double safeAmount =
    rawAmount.abs() < 0.005 ? 0.0 : rawAmount;

    final String amount = fmt.format(safeAmount);
    final PdfColor amountColor =
    isCredit ? PdfColors.green : PdfColors.red;

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(24),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // -------------------------------------------------
              // HEADER
              // -------------------------------------------------
              pw.Text(
                "Transaction Details",
                style: pw.TextStyle(
                  font: font,
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromInt(AppColors.primary.value),
                ),
              ),

              pw.SizedBox(height: 6),

              pw.Text(
                "Voucher #${row.voucherNo}",
                textDirection: _dir("Voucher #${row.voucherNo}"),
                style: pw.TextStyle(
                  font: font,
                  fontSize: 14,
                  color: PdfColor.fromInt(AppColors.textDark.value),
                ),
              ),

              pw.Divider(color: PdfColors.grey300, height: 24),

              // -------------------------------------------------
              // INFO
              // -------------------------------------------------
              _infoBlock("Name", row.name.isNotEmpty ? row.name : "-"),
              _infoBlock("Date", row.date.isNotEmpty ? row.date : "-"),
              _infoBlock("Currency",
                  row.currency.isNotEmpty ? row.currency : "-"),

              if ((row.description ?? "").isNotEmpty)
                _infoBlock("Description", row.description!),

              pw.SizedBox(height: 24),

              // -------------------------------------------------
              // AMOUNT
              // -------------------------------------------------
              pw.Center(
                child: pw.Text(
                  "${isCredit ? '+' : '-'}$amount",
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 36,
                    fontWeight: pw.FontWeight.bold,
                    color: amountColor,
                  ),
                ),
              ),

              pw.SizedBox(height: 30),
              pw.Divider(color: PdfColors.grey400),

              pw.Center(
                child: pw.Text(
                  "Generated by Mahfooz Accounts",
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 10,
                    color: PdfColors.grey600,
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );

    // -----------------------------------------------------------
    // SAVE
    // -----------------------------------------------------------
    final dir = await getTemporaryDirectory();
    final file = File("${dir.path}/tx_details_${row.voucherNo}.pdf");

    await file.writeAsBytes(await pdf.save());
    return file;
  }

  // -----------------------------------------------------------
  // INFO BLOCK
  // -----------------------------------------------------------
  pw.Widget _infoBlock(String title, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            textDirection: _dir(title),
            style: pw.TextStyle(
              font: _unicodeFont!,
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey700,
            ),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            textDirection: _dir(value),
            style: pw.TextStyle(
              font: _unicodeFont!,
              fontSize: 14,
              color: PdfColor.fromInt(AppColors.textDark.value),
            ),
          ),
        ],
      ),
    );
  }
}
